#!/usr/bin/env bash
# Local-dev wiring for a project: pull its db-server/<project>/db-client bundle from AWS
# Secrets Manager, write the mTLS client cert/key to disk, and emit a .env.local with the
# Prisma 7 connection strings (pooled DATABASE_URL + session DIRECT_DATABASE_URL).
# Mirrors docs/amplify-nextjs-setup.md §1 — for a Next.js/Prisma app locally AND for DBeaver
# (also writes client.pk8, the PKCS#8 DER key that DBeaver/JDBC need; see docs/dbeaver-setup.md).
#
# Usage:  ./scripts/dev-env.sh <project> [out_dir]
#   <project>   e.g. myapp        (secret = db-server/<project>/db-client)
#   [out_dir]   where to write client.crt/key + .env.local (default: ./.dev/<project>)
# Env:    AWS_REGION (default eu-central-1); AWS_PROFILE if not your default profile.
# Needs:  aws cli, jq.
set -euo pipefail

PROJECT="${1:?usage: $0 <project> [out_dir]   e.g. $0 myapp}"
OUT="${2:-.dev/$PROJECT}"
REGION="${AWS_REGION:-eu-central-1}"
SECRET="db-server/${PROJECT}/db-client"

echo "==> Fetching ${SECRET} from Secrets Manager (${REGION})…"
JSON="$(aws secretsmanager get-secret-value --region "$REGION" \
  --secret-id "$SECRET" --query SecretString --output text)"

host="$(jq -r .host   <<<"$JSON")"
port="$(jq -r .port   <<<"$JSON")"
db="$(  jq -r .dbname <<<"$JSON")"
user="$(jq -r .user     <<<"$JSON")"   # raw values for the DBeaver field block below
pass="$(jq -r .password <<<"$JSON")"
# URL-encode user + password so special characters can't break the connection string.
encuser="$(jq -r '.user|@uri'     <<<"$JSON")"
encpass="$(jq -r '.password|@uri' <<<"$JSON")"

mkdir -p "$OUT"
crt="$OUT/client.crt"; key="$OUT/client.key"
jq -r .client_cert <<<"$JSON" > "$crt"
jq -r .client_key  <<<"$JSON" > "$key"
chmod 600 "$key"                       # libpq/Prisma refuse a group/world-readable key
# DBeaver / any JDBC client (pgjdbc) need the key as PKCS#8 DER, not PEM. Generate it too.
pk8="$OUT/client.pk8"
if command -v openssl >/dev/null 2>&1; then
  openssl pkcs8 -topk8 -inform PEM -outform DER -in "$key" -out "$pk8" -nocrypt 2>/dev/null \
    && chmod 600 "$pk8" || echo "  warn: could not generate client.pk8 (DBeaver needs PKCS#8 DER)"
else
  echo "  note: install openssl to also generate client.pk8 for DBeaver/JDBC"
fi
# Absolute paths so the URLs/clients work regardless of where they're launched from.
acrt="$(cd "$(dirname "$crt")" && pwd)/$(basename "$crt")"
akey="$(cd "$(dirname "$key")" && pwd)/$(basename "$key")"
apk8="$(cd "$OUT" && pwd)/client.pk8"

# DBeaver/pgjdbc uses LibPQFactory when a client cert is present, which REQUIRES an explicit
# root cert (it won't fall back to the JVM truststore). Point it at the OS CA bundle that
# already trusts the public Let's Encrypt SERVER cert. (psql doesn't need this — sslrootcert=system.)
cabundle=""
for c in "${SSL_CERT_FILE:-}" /etc/ssl/cert.pem /opt/homebrew/etc/ca-certificates/cert.pem \
         /opt/homebrew/etc/openssl@3/cert.pem /etc/ssl/certs/ca-certificates.crt; do
  [ -n "$c" ] && [ -f "$c" ] && { cabundle="$c"; break; }
done

# No sslrootcert: the SERVER cert is public Let's Encrypt, validated by the system/Node trust
# store (docs/amplify §1). We DO present the client cert/key for mTLS.
tls="sslmode=verify-full&sslcert=${acrt}&sslkey=${akey}"
APP="postgresql://${encuser}:${encpass}@${host}:${port}/${db}?connection_limit=1&${tls}"
DIRECT="postgresql://${encuser}:${encpass}@${host}:${port}/${db}_session?${tls}"

env_file="$OUT/.env.local"
( umask 077
  cat > "$env_file" <<EOF
# Generated by scripts/dev-env.sh for ${PROJECT} local dev — DO NOT COMMIT.
# Pooled (transaction) — Prisma Client / app runtime:
DATABASE_URL="${APP}"
# Direct (session) — Prisma CLI migrations (prisma.config.ts):
DIRECT_DATABASE_URL="${DIRECT}"
# Prisma 6.x? append &pgbouncer=true to DATABASE_URL and use directUrl instead.
EOF
)

echo "✓ wrote ${crt}, ${key}, ${pk8}, and ${env_file}"
echo "  Next.js:  cp ${env_file} <your-next-app>/.env.local   (or: set -a; . ${env_file}; set +a)"
echo
echo "DATABASE_URL=${APP}"
echo "DIRECT_DATABASE_URL=${DIRECT}"
echo
echo "── DBeaver (PostgreSQL) — full steps in docs/dbeaver-setup.md ──"
echo "  Host: ${host}    Port: ${port}"
echo "  Database: ${db}_session   (interactive; use ${db} for app-like pooled)"
echo "  Username: ${user}"
echo "  Password: ${pass}"
echo "  SSL: enable, mode=verify-full"
echo "  CA Certificate: ${cabundle:-<your OS CA bundle, e.g. /etc/ssl/cert.pem>}"
echo "  Client Certificate: ${acrt}"
echo "  Client Key (PKCS#8): ${apk8}"
